services:
  shoutrrr:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:${API_PORT}:${API_PORT}"
    volumes:
      - ./src:/app/src
    environment:
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      API_KEY: ${API_KEY}
      API_PORT: ${API_PORT}
    command: sh -c 'uvicorn app:app --host 0.0.0.0 --port ${API_PORT}'
